name: Daily E2E Tests

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC daily
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Use the appropriate Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run E2E Tests with Mochawesome
      id: e2e-tests
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_VERIFICATION_TOKEN }}
      run: |
        SLACK_TOKEN=${{ secrets.SLACK_VERIFICATION_TOKEN }} npx cypress run --reporter mochawesome --reporter-options reportDir=reports,overwrite=false,html=false,json=true
        npx mochawesome-merge reports/*.json > merged-report.json
        npx marge merged-report.json -o reports/html
        mkdir -p docs
        mv reports/html/* docs/

    - name: Push Web App
      run: |
        cd docs
        # cp -r ../build/web/ docs
        git config user.name "e2e"
        git config user.email "e2e@github.com"
        git add .
        git commit -m "Publish test report/e2e-busybe"
        git push origin dashboard

    # - name: Upload Test Report as Artifact
    #   if: always() # Upload even if tests pass
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: E2E-Test-Report
    #     path: docs
    #     retention-days: 7 # Keep report for 7 days
    
    # - name: Disable Jekyll processing
    #   run: touch docs/.nojekyll

    # - name: Deploy Report to GitHub Pages
    #   if: always()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs

    - name: Notify Slack on deployment failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "🚨 BusyBe E2E Tests failed for ${{ github.repository }} on ${{ github.ref }}: ${{ github.run_id }}"

